version: "3.8"
services:
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - ${PGDB_PORT:-5432}:5432
    volumes:
      - pgdb-volume:/data/postgres
    environment:
      POSTGRES_USER: ${PGDB_USER:-admin}
      POSTGRES_PASSWORD: ${PGDB_PASSWORD:-12345678}
      POSTGRES_DB: ${PGDB_NAME:-pgdb}
      PGDATA: /data/postgres

    networks:
      - netmain
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "postgresdb","-p","5432","-d","${PGDB_NAME:-pgdb}","-U","${PGDB_USER:-admin}", "-q" ]
      timeout: 20s
      interval: 3s
      retries: 15
    restart: always

  migrations:
    image: gotodotask/migrations:latest
    container_name: todotask-migrations
    build:
      context: ./internal/migrations
      dockerfile: Dockerfile
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://${PGDB_USER:-admin}:${PGDB_PASSWORD:-12345678}@postgresdb:5432/${PGDB_NAME:-pgdb}?sslmode=disable
    command: [ "-v","--dir","sqls","up" ]
    depends_on:
      - postgresdb
    networks:
      - netmain

  user:
    image: gotodotask/user:latest
    container_name: gotodotask-user
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: "1.20"
    ports:
      - ${USER_GRPC_PORT:-6060}:3000
      - ${USER_HTTP_PORT:-7070}:4000
    environment:
      LOG_REQUEST: true
      JWT_SECRET: DF6806F10F45D95ACF44
      DATABASE_URL: postgres://${PGDB_USER:-admin}:${PGDB_PASSWORD:-12345678}@postgresdb:5432/${PGDB_NAME:-pgdb}?sslmode=disable
    command:
      - user
    networks:
      - netmain
    depends_on:
      - postgresdb
      - migrations
    restart: always

  taskmanager:
    image: gotodotask/taskmanager:latest
    container_name: gotodotask-taskmanager
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: "1.20"
    ports:
      - ${TASK_MANAGER_GRPC_PORT:-5050}:3000
      - ${TASK_MANAGER_HTTP_PORT:-4040}:4000
    environment:
      LOG_REQUEST: true
      JWT_SECRET: DF6806F10F45D95ACF44
      DATABASE_URL: postgres://${PGDB_USER:-admin}:${PGDB_PASSWORD:-12345678}@postgresdb:5432/${PGDB_NAME:-pgdb}?sslmode=disable
    command:
      - taskmanager
    networks:
      - netmain
    depends_on:
      - postgresdb
      - user
      - migrations
    restart: always
networks:
  netmain:
    driver: bridge

volumes:
  pgdb-volume: