version: "3.8"
services:
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - ${PGDB_PORT:-5432}:5432
    volumes:
      - pgdb-volume:/data/postgres
    environment:
      POSTGRES_USER: ${PGDB_USER:-admin}
      POSTGRES_PASSWORD: ${PGDB_PASSWORD:-12345678}
      POSTGRES_DB: ${PGDB_NAME:-pgdb}
      PGDATA: /data/postgres

    networks:
      - netproxy
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "postgresdb","-p","5432","-d","${PGDB_NAME:-pgdb}","-U","${PGDB_USER:-admin}", "-q" ]
      timeout: 20s
      interval: 3s
      retries: 15
    restart: always

  migrations:
    image: gotodotask/migrations:latest
    container_name: todotask-migrations
    build:
      context: ./internal/migrations
      dockerfile: Dockerfile
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://${PGDB_USER:-admin}:${PGDB_PASSWORD:-12345678}@postgresdb:5432/${PGDB_NAME:-pgdb}?sslmode=disable
    command: [ "-v","--dir","sqls","up" ]
    depends_on:
      - postgresdb
    networks:
      - netproxy
    labels:
      - traefik.enable=false

  user:
    image: gotodotask/user:latest
    container_name: gotodotask-user
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: "1.20"
    ports:
      - ${USER_GRPC_PORT:-6060}:3000
      - ${USER_HTTP_PORT:-7070}:4000
    environment:
      LOG_REQUEST: true
      JWT_SECRET: DF6806F10F45D95ACF44
      DATABASE_URL: postgres://${PGDB_USER:-admin}:${PGDB_PASSWORD:-12345678}@postgresdb:5432/${PGDB_NAME:-pgdb}?sslmode=disable
    command:
      - user
    networks:
      - netproxy
    depends_on:
      - postgresdb
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.entrypoints=web"
      - "traefik.http.routers.user.rule=PathPrefix(`/v1/user`)"
      - "traefik.http.services.user.loadbalancer.server.port=4000"
      - "traefik.docker.network=netproxy"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=GET,POST,DELETE,OPTIONS,PUT"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=Content-Type"
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.cors.headers.addVaryHeader=true"
      - "traefik.http.routers.user.middlewares=cors"

  taskmanager:
    image: gotodotask/taskmanager:latest
    container_name: gotodotask-taskmanager
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: "1.20"
    ports:
      - ${TASK_MANAGER_GRPC_PORT:-3030}:3000
      - ${TASK_MANAGER_HTTP_PORT:-4040}:4000
    environment:
      LOG_REQUEST: true
      JWT_SECRET: DF6806F10F45D95ACF44
      DATABASE_URL: postgres://${PGDB_USER:-admin}:${PGDB_PASSWORD:-12345678}@postgresdb:5432/${PGDB_NAME:-pgdb}?sslmode=disable
    command:
      - taskmanager
    networks:
      - netproxy
    depends_on:
      - postgresdb
      - user
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taskmanager.entrypoints=web"
      - "traefik.http.routers.taskmanager.rule=PathPrefix(`/v1/todotask`)"
      - "traefik.http.services.taskmanager.loadbalancer.server.port=4000"
      - "traefik.docker.network=netproxy"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=GET,POST,DELETE,OPTIONS,PUT"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=Content-Type"
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.cors.headers.addVaryHeader=true"
      - "traefik.http.routers.taskmanager.middlewares=cors"

  traefik:
    image: "traefik:2.9.8"
    container_name: gotodotask-traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
#      - "--providers.docker.useBindPortIP=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - netproxy
networks:
  netproxy:
    driver: bridge
volumes:
  pgdb-volume: